CREATE TABLE IF NOT EXISTS analytics_monthly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    metric_key VARCHAR(100) NOT NULL,
    metric_value NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analytics_monthly_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_analytics_monthly_org_period_start
    ON analytics_monthly (organization_id, period_start);
