CREATE TABLE IF NOT EXISTS facial_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    embedding_ciphertext BYTEA NOT NULL,
    kdf_salt BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_facial_embeddings_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_facial_embeddings_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);
