CREATE TABLE IF NOT EXISTS engagement_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    score NUMERIC(5, 2) NOT NULL,
    attended_count INT NOT NULL,
    total_count INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_engagement_scores_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_engagement_scores_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_engagement_scores_org_period
    ON engagement_scores (organization_id, period_start);

CREATE UNIQUE INDEX IF NOT EXISTS idx_engagement_scores_org_user_period
    ON engagement_scores (organization_id, user_id, period_start);
